{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP8sv/TE1pTAltYCztg4fpy",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ajaychandar14/youtubeproject_1/blob/main/Youtubeproject.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "HQf_6zjZE0tl"
      },
      "outputs": [],
      "source": [
        "from googleapiclient.discovery import build\n",
        "import pymongo\n",
        "import psycopg2\n",
        "import pandas as pd\n",
        "import streamlit as st\n",
        "\n",
        "\n",
        "#API key connection\n",
        "def Api_connect():\n",
        "    Api_Id=\"AIzaSyAV0lSB_yLR95vx9EFcs4J8_cd1iun9DS4\"\n",
        "    api_service_name=\"youtube\"\n",
        "    api_version=\"v3\"\n",
        "\n",
        "    youtube=build(api_service_name,api_version,developerKey=Api_Id)\n",
        "\n",
        "    return youtube\n",
        "\n",
        "youtube=Api_connect()\n",
        "\n",
        "\n",
        "#get channels information\n",
        "def get_channel_info(channel_id):\n",
        "\n",
        "    request=youtube.channels().list(\n",
        "                    part=\"snippet,ContentDetails,statistics\",\n",
        "                    id=channel_id\n",
        "    )\n",
        "    response=request.execute()\n",
        "\n",
        "    for i in response['items']:\n",
        "        data=dict(Channel_Names=i[\"snippet\"][\"title\"],\n",
        "                Channel_Id=i[\"id\"],\n",
        "                Subscribers=i['statistics']['subscriberCount'],\n",
        "                Views=i[\"statistics\"][\"viewCount\"],\n",
        "                Total_Videos=i[\"statistics\"][\"videoCount\"],\n",
        "                Channel_Description=i[\"snippet\"][\"description\"],\n",
        "                Playlist_Id=i[\"contentDetails\"][\"relatedPlaylists\"][\"uploads\"])\n",
        "    return data\n",
        "\n",
        "\n",
        "#get video ids\n",
        "def get_videos_ids(channel_id):\n",
        "    video_ids=[]\n",
        "    response=youtube.channels().list(id=channel_id,\n",
        "                                    part='contentDetails').execute()\n",
        "    Playlist_Id=response['items'][0]['contentDetails']['relatedPlaylists']['uploads']\n",
        "\n",
        "    next_page_token=None\n",
        "\n",
        "    while True:\n",
        "        response1=youtube.playlistItems().list(\n",
        "                                            part='snippet',\n",
        "                                            playlistId=Playlist_Id,\n",
        "                                            maxResults=50,\n",
        "                                            pageToken=next_page_token).execute()\n",
        "        for i in range(len(response1['items'])):\n",
        "            video_ids.append(response1['items'][i]['snippet']['resourceId']['videoId'])\n",
        "        next_page_token=response1.get('nextPageToken')\n",
        "        if next_page_token is None:\n",
        "            break\n",
        "    return video_ids\n",
        "\n",
        "\n",
        "#get video information\n",
        "def get_video_info(video_ids):\n",
        "    video_data=[]\n",
        "    for video_id in video_ids:\n",
        "        request=youtube.videos().list(\n",
        "            part=\"snippet,ContentDetails,statistics\",\n",
        "            id=video_id\n",
        "        )\n",
        "        response=request.execute()\n",
        "\n",
        "        for item in response[\"items\"]:\n",
        "            data=dict(Channel_Name=item['snippet']['channelTitle'],\n",
        "                    Channel_Id=item['snippet']['channelId'],\n",
        "                    Video_Id=item['id'],\n",
        "                    Title=item['snippet']['title'],\n",
        "                    Thumbnail=item['snippet']['thumbnails']['default']['url'],\n",
        "                    Description=item['snippet'].get('description'),\n",
        "                    Published_Date=item['snippet']['publishedAt'],\n",
        "                    Duration=item['contentDetails']['duration'],\n",
        "                    Views=item['statistics'].get('viewCount'),\n",
        "                    Likes=item['statistics'].get('likeCount'),\n",
        "                    Comments=item['statistics'].get('commentCount'),\n",
        "                    Favorite_Count=item['statistics']['favoriteCount'],\n",
        "                    Definition=item['contentDetails']['definition'],\n",
        "                    Caption_Status=item['contentDetails']['caption']\n",
        "                    )\n",
        "            video_data.append(data)\n",
        "    return video_data\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "#get comment information\n",
        "def get_comment_info(video_ids):\n",
        "    Comment_data=[]\n",
        "    try:\n",
        "        for video_id in video_ids:\n",
        "            request=youtube.commentThreads().list(\n",
        "                part=\"snippet\",\n",
        "                videoId=video_id,\n",
        "                maxResults=50\n",
        "            )\n",
        "            response=request.execute()\n",
        "\n",
        "            for item in response['items']:\n",
        "                data=dict(Comment_Id=item['snippet']['topLevelComment']['id'],\n",
        "                        Video_Id=item['snippet']['topLevelComment']['snippet']['videoId'],\n",
        "                        Comment_Text=item['snippet']['topLevelComment']['snippet']['textDisplay'],\n",
        "                        Comment_Author=item['snippet']['topLevelComment']['snippet']['authorDisplayName'],\n",
        "                        Comment_Published=item['snippet']['topLevelComment']['snippet']['publishedAt'])\n",
        "\n",
        "                Comment_data.append(data)\n",
        "    except:\n",
        "        pass\n",
        "    return Comment_data\n",
        "\n",
        "\n",
        "#get_playlist_details\n",
        "\n",
        "def get_playlist_details(channel_id):\n",
        "    next_page_token=None\n",
        "    All_data=[]\n",
        "    while True:\n",
        "        request=youtube.playlists().list(\n",
        "            part='snippet,contentDetails',\n",
        "            channelId=channel_id,\n",
        "            maxResults=50,\n",
        "            pageToken=next_page_token\n",
        "        )\n",
        "        response=request.execute()\n",
        "\n",
        "        for item in response['items']:\n",
        "            data=dict(Playlist_Id=item['id'],\n",
        "                    Title=item['snippet']['title'],\n",
        "                    Channel_Id=item['snippet']['channelId'],\n",
        "                    Channel_Name=item['snippet']['channelTitle'],\n",
        "                    PublishedAt=item['snippet']['publishedAt'],\n",
        "                    Video_Count=item['contentDetails']['itemCount'])\n",
        "            All_data.append(data)\n",
        "\n",
        "        next_page_token=response.get('nextPageToken')\n",
        "        if next_page_token is None:\n",
        "            break\n",
        "    return All_data\n",
        "\n",
        "\n",
        "#upload to mongoDB\n",
        "\n",
        "client=pymongo.MongoClient(\"mongodb://localhost:27017\")\n",
        "db=client[\"Youtube_data\"]\n",
        "\n",
        "def channel_details(channel_id):\n",
        "    ch_details=get_channel_info(channel_id)\n",
        "    pl_details=get_playlist_details(channel_id)\n",
        "    vi_ids=get_videos_ids(channel_id)\n",
        "    vi_details=get_video_info(vi_ids)\n",
        "    com_details=get_comment_info(vi_ids)\n",
        "\n",
        "    coll1=db[\"channel_details\"]\n",
        "    coll1.insert_one({\"channel_information\":ch_details,\"playlist_information\":pl_details,\n",
        "                      \"video_information\":vi_details,\"comment_information\":com_details})\n",
        "    return \"upload completed successfully\"\n",
        "\n",
        "\n",
        "#Table creation for channels,playlists,videos,comments\n",
        "def channels_table():\n",
        "    mydb=psycopg2.connect(host=\"localhost\",\n",
        "                        user=\"postgres\",\n",
        "                        password=\"ajay\",\n",
        "                        database=\"youtube_data\",\n",
        "                        port=\"5432\")\n",
        "    cursor=mydb.cursor()\n",
        "\n",
        "    drop_query='''drop table if exists channels'''\n",
        "    cursor.execute(drop_query)\n",
        "    mydb.commit()\n",
        "\n",
        "\n",
        "    try:\n",
        "        create_query='''create table if not exists channels(Channel_Names varchar(100),\n",
        "                                                            Channel_Id varchar(80) primary key,\n",
        "                                                            Subscribers bigint,\n",
        "                                                            Views bigint,\n",
        "                                                            Total_Videos int,\n",
        "                                                            Channel_Description text,\n",
        "                                                            Playlist_Id varchar(80)\n",
        "                                                            )'''\n",
        "        cursor.execute(create_query)\n",
        "        mydb.commit()\n",
        "    except:\n",
        "        print(\"channel table already created\")\n",
        "\n",
        "\n",
        "    ch_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for ch_data in coll1.find({},{\"_id\":0,\"channel_information\":1}):\n",
        "        ch_list.append(ch_data[\"channel_information\"])\n",
        "    df=pd.DataFrame(ch_list)\n",
        "\n",
        "\n",
        "\n",
        "    for index,row in df.iterrows():\n",
        "        insert_query='''insert into channels(Channel_Names ,\n",
        "                                            Channel_Id,\n",
        "                                            Subscribers,\n",
        "                                            Views,\n",
        "                                            Total_Videos,\n",
        "                                            Channel_Description,\n",
        "                                            Playlist_Id)\n",
        "\n",
        "                                            values(%s,%s,%s,%s,%s,%s,%s)'''\n",
        "        values=(row['Channel_Names'],\n",
        "                row['Channel_Id'],\n",
        "                row['Subscribers'],\n",
        "                row['Views'],\n",
        "                row['Total_Videos'],\n",
        "                row['Channel_Description'],\n",
        "                row['Playlist_Id'])\n",
        "\n",
        "        try:\n",
        "            cursor.execute(insert_query,values)\n",
        "            mydb.commit()\n",
        "\n",
        "        except:\n",
        "            print(\"Channel values are already inserted\")\n",
        "\n",
        "def playlist_table():\n",
        "\n",
        "    mydb=psycopg2.connect(host=\"localhost\",\n",
        "                        user=\"postgres\",\n",
        "                        password=\"ajay\",\n",
        "                        database=\"youtube_data\",\n",
        "                        port=\"5432\")\n",
        "    cursor=mydb.cursor()\n",
        "\n",
        "    drop_query='''drop table if exists playlists'''\n",
        "    cursor.execute(drop_query)\n",
        "    mydb.commit()\n",
        "\n",
        "\n",
        "\n",
        "    create_query='''create table if not exists playlists(Playlist_Id varchar(100) primary key,\n",
        "                                                        Title varchar(100),\n",
        "                                                        Channel_Id varchar(100),\n",
        "                                                        Channel_Name varchar(100),\n",
        "                                                        PublishedAt timestamp,\n",
        "                                                        Video_Count int\n",
        "                                                        )'''\n",
        "\n",
        "    cursor.execute(create_query)\n",
        "    mydb.commit()\n",
        "\n",
        "    pl_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for pl_data in coll1.find({},{\"_id\":0,\"playlist_information\":1}):\n",
        "        for i in range(len(pl_data[\"playlist_information\"])):\n",
        "            pl_list.append(pl_data[\"playlist_information\"][i])\n",
        "\n",
        "    df1=pd.DataFrame(pl_list)\n",
        "\n",
        "\n",
        "\n",
        "    for index,row in df1.iterrows():\n",
        "            insert_query='''insert into playlists(Playlist_Id,\n",
        "                                                Title,\n",
        "                                                Channel_Id,\n",
        "                                                Channel_Name,\n",
        "                                                PublishedAt ,\n",
        "                                                Video_Count\n",
        "                                                )\n",
        "\n",
        "                                                values(%s,%s,%s,%s,%s,%s)'''\n",
        "            values=(row['Playlist_Id'],\n",
        "                    row['Title'],\n",
        "                    row['Channel_Id'],\n",
        "                    row['Channel_Name'],\n",
        "                    row['PublishedAt'],\n",
        "                    row['Video_Count']\n",
        "                    )\n",
        "\n",
        "\n",
        "            cursor.execute(insert_query,values)\n",
        "            mydb.commit()\n",
        "\n",
        "\n",
        "def videos_table():\n",
        "\n",
        "    mydb=psycopg2.connect(host=\"localhost\",\n",
        "                        user=\"postgres\",\n",
        "                        password=\"ajay\",\n",
        "                        database=\"youtube_data\",\n",
        "                        port=\"5432\")\n",
        "    cursor=mydb.cursor()\n",
        "\n",
        "    drop_query='''drop table if exists videos'''\n",
        "    cursor.execute(drop_query)\n",
        "    mydb.commit()\n",
        "\n",
        "\n",
        "    create_query='''create table if not exists videos(Channel_Name varchar(100),\n",
        "                                                    Channel_Id varchar(100),\n",
        "                                                    Video_Id varchar(30),\n",
        "                                                    Title varchar(150),\n",
        "                                                    Thumbnail varchar(200),\n",
        "                                                    Description text,\n",
        "                                                    Published_Date timestamp,\n",
        "                                                    Duration interval,\n",
        "                                                    Views bigint,\n",
        "                                                    Likes bigint,\n",
        "                                                    Comments int,\n",
        "                                                    Favorite_Count int,\n",
        "                                                    Definition varchar(10),\n",
        "                                                    Caption_Status varchar(50)\n",
        "                                                        )'''\n",
        "\n",
        "    cursor.execute(create_query)\n",
        "    mydb.commit()\n",
        "\n",
        "    vi_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for vi_data in coll1.find({},{\"_id\":0,\"video_information\":1}):\n",
        "        for i in range(len(vi_data[\"video_information\"])):\n",
        "            vi_list.append(vi_data[\"video_information\"][i])\n",
        "\n",
        "    df2=pd.DataFrame(vi_list)\n",
        "\n",
        "\n",
        "    for index,row in df2.iterrows():\n",
        "        insert_query='''insert into videos(Channel_Name ,\n",
        "                                            Channel_Id,\n",
        "                                            Video_Id,\n",
        "                                            Title,\n",
        "                                            Thumbnail,\n",
        "                                            Description,\n",
        "                                            Published_Date,\n",
        "                                            Duration,\n",
        "                                            Views,\n",
        "                                            Likes,\n",
        "                                            Comments,\n",
        "                                            Favorite_Count,\n",
        "                                            Definition,\n",
        "                                            Caption_Status\n",
        "                                            )\n",
        "\n",
        "                                            values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'''\n",
        "        values=(row['Channel_Name'],\n",
        "                row['Channel_Id'],\n",
        "                row['Video_Id'],\n",
        "                row['Title'],\n",
        "                row['Thumbnail'],\n",
        "                row['Description'],\n",
        "                row['Published_Date'],\n",
        "                row['Duration'],\n",
        "                row['Views'],\n",
        "                row['Likes'],\n",
        "                row['Comments'],\n",
        "                row['Favorite_Count'],\n",
        "                row['Definition'],\n",
        "                row['Caption_Status']\n",
        "                )\n",
        "        cursor.execute(insert_query,values)\n",
        "        mydb.commit()\n",
        "\n",
        "\n",
        "def comments_table():\n",
        "\n",
        "    mydb=psycopg2.connect(host=\"localhost\",\n",
        "                        user=\"postgres\",\n",
        "                        password=\"ajay\",\n",
        "                        database=\"youtube_data\",\n",
        "                        port=\"5432\")\n",
        "    cursor=mydb.cursor()\n",
        "\n",
        "    drop_query='''drop table if exists comments'''\n",
        "    cursor.execute(drop_query)\n",
        "    mydb.commit()\n",
        "\n",
        "\n",
        "\n",
        "    create_query='''create table if not exists comments(Comment_Id varchar(100) primary key,\n",
        "                                                        Video_Id varchar(50),\n",
        "                                                        Comment_Text text,\n",
        "                                                        Comment_Author varchar(150),\n",
        "                                                        Comment_Published timestamp\n",
        "                                                        )'''\n",
        "\n",
        "    cursor.execute(create_query)\n",
        "    mydb.commit()\n",
        "\n",
        "    com_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for com_data in coll1.find({},{\"_id\":0,\"comment_information\":1}):\n",
        "        for i in range(len(com_data[\"comment_information\"])):\n",
        "            com_list.append(com_data[\"comment_information\"][i])\n",
        "\n",
        "    df3=pd.DataFrame(com_list)\n",
        "\n",
        "\n",
        "\n",
        "    for index,row in df3.iterrows():\n",
        "            insert_query='''insert into comments(Comment_Id,\n",
        "                                                Video_Id,\n",
        "                                                Comment_Text,\n",
        "                                                Comment_Author,\n",
        "                                                Comment_Published\n",
        "                                                )\n",
        "\n",
        "                                                values(%s,%s,%s,%s,%s)'''\n",
        "            values=(row['Comment_Id'],\n",
        "                    row['Video_Id'],\n",
        "                    row['Comment_Text'],\n",
        "                    row['Comment_Author'],\n",
        "                    row['Comment_Published']\n",
        "                    )\n",
        "\n",
        "\n",
        "            cursor.execute(insert_query,values)\n",
        "            mydb.commit()\n",
        "\n",
        "\n",
        "def tables():\n",
        "    channels_table()\n",
        "    playlist_table()\n",
        "    videos_table()\n",
        "    comments_table()\n",
        "\n",
        "    return\"Tables Created Successfully\"\n",
        "\n",
        "\n",
        "def show_channels_table():\n",
        "    ch_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for ch_data in coll1.find({},{\"_id\":0,\"channel_information\":1}):\n",
        "        ch_list.append(ch_data[\"channel_information\"])\n",
        "    df=st.dataframe(ch_list)\n",
        "\n",
        "    return df\n",
        "\n",
        "def show_playlists_table():\n",
        "    pl_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for pl_data in coll1.find({},{\"_id\":0,\"playlist_information\":1}):\n",
        "        for i in range(len(pl_data[\"playlist_information\"])):\n",
        "            pl_list.append(pl_data[\"playlist_information\"][i])\n",
        "    df1=st.dataframe(pl_list)\n",
        "\n",
        "    return df1\n",
        "\n",
        "\n",
        "def show_videos_table():\n",
        "    vi_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for vi_data in coll1.find({},{\"_id\":0,\"video_information\":1}):\n",
        "        for i in range(len(vi_data[\"video_information\"])):\n",
        "            vi_list.append(vi_data[\"video_information\"][i])\n",
        "\n",
        "    df2=st.dataframe(vi_list)\n",
        "\n",
        "    return df2\n",
        "\n",
        "def show_comments_table():\n",
        "    com_list=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for com_data in coll1.find({},{\"_id\":0,\"comment_information\":1}):\n",
        "        for i in range(len(com_data[\"comment_information\"])):\n",
        "            com_list.append(com_data[\"comment_information\"][i])\n",
        "\n",
        "    df3=st.dataframe(com_list)\n",
        "\n",
        "    return df3\n",
        "\n",
        "#streamlit part\n",
        "\n",
        "with st.sidebar:\n",
        "    st.title(\":red[YOUTUBE DATA HAVERSTING AND WAREHOUSING]\")\n",
        "    st.header(\"Skill Take Away\")\n",
        "    st.caption(\"Python Scripting\")\n",
        "    st.caption(\"Data Collection\")\n",
        "    st.caption(\"MongoDB\")\n",
        "    st.caption(\"API Integration\")\n",
        "    st.caption(\"Data Management using MongoDB and SQL\")\n",
        "\n",
        "channel_id=st.text_input(\"Enter the channel ID\")\n",
        "\n",
        "if st.button(\"collect and store data\"):\n",
        "    ch_ids=[]\n",
        "    db=client[\"Youtube_data\"]\n",
        "    coll1=db[\"channel_details\"]\n",
        "    for ch_data in coll1.find({},{\"_id\":0,\"channel_information\":1}):\n",
        "        ch_ids.append(ch_data[\"channel_information\"][\"Channel_Id\"])\n",
        "\n",
        "    if channel_id in ch_ids:\n",
        "        st.success(\"Channel Details of the given channel id already exists\")\n",
        "\n",
        "    else:\n",
        "        insert=channel_details(channel_id)\n",
        "        st.success(insert)\n",
        "\n",
        "if st.button(\"Migrate to Sql\"):\n",
        "    Table=tables()\n",
        "    st.success(Table)\n",
        "\n",
        "show_table=st.radio(\"SELECT THE TABLE FOR VIEW\",(\"CHANNELS\",\"PLAYLISTS\",\"VIDEOS\",\"COMMENTS\"))\n",
        "\n",
        "if show_table==\"CHANNELS\":\n",
        "    show_channels_table()\n",
        "\n",
        "elif show_table==\"PLAYLISTS\":\n",
        "    show_playlists_table()\n",
        "\n",
        "elif show_table==\"VIDEOS\":\n",
        "    show_videos_table()\n",
        "\n",
        "elif show_table==\"COMMENTS\":\n",
        "    show_comments_table()\n",
        "\n",
        "\n",
        "#SQL Connection\n",
        "\n",
        "mydb=psycopg2.connect(host=\"localhost\",\n",
        "                        user=\"postgres\",\n",
        "                        password=\"ajay\",\n",
        "                        database=\"youtube_data\",\n",
        "                        port=\"5432\")\n",
        "cursor=mydb.cursor()\n",
        "\n",
        "question=st.selectbox(\"Select your question\",(\"1. All the videos and the channel name\",\n",
        "                                              \"2. channels with most number of videos\",\n",
        "                                              \"3. 10 most viewed videos\",\n",
        "                                              \"4. comments in each videos\",\n",
        "                                              \"5. videos with highest likes\",\n",
        "                                              \"6. likes of all videos\",\n",
        "                                              \"7. views of each channel\",\n",
        "                                              \"8. videos published in the year of 2022 \",\n",
        "                                              \"9. average duration of all videos in each channel\",\n",
        "                                              \"10. videos with highest number of comments\"))\n",
        "\n",
        "if question==\"1. All the videos and the channel name\":\n",
        "    query1='''select title as videos,channel_name as channelname from videos'''\n",
        "    cursor.execute(query1)\n",
        "    mydb.commit()\n",
        "    t1=cursor.fetchall()\n",
        "    df=pd.DataFrame(t1,columns=[\"video title\",\"channel name\"])\n",
        "    st.write(df)\n",
        "\n",
        "elif question==\"2. channels with most number of videos\":\n",
        "    query2='''select channel_names as channelname,total_videos as no_videos from channels\n",
        "                order by total_videos desc'''\n",
        "    cursor.execute(query2)\n",
        "    mydb.commit()\n",
        "    t2=cursor.fetchall()\n",
        "    df2=pd.DataFrame(t2,columns=[\"channel name\",\"No of videos\"])\n",
        "    st.write(df2)\n",
        "\n",
        "elif question==\"3. 10 most viewed videos\":\n",
        "    query3='''select views as views,channel_name as channelname,title as videotitle from videos\n",
        "            where views is not null order by views desc limit 10'''\n",
        "    cursor.execute(query3)\n",
        "    mydb.commit()\n",
        "    t3=cursor.fetchall()\n",
        "    df3=pd.DataFrame(t3,columns=[\"views\",\"channel name\",\"videotitle\"])\n",
        "    st.write(df3)\n",
        "\n",
        "elif question==\"4. comments in each videos\":\n",
        "    query4='''select comments as no_comments,title as videotitle from videos where comments is not null'''\n",
        "    cursor.execute(query4)\n",
        "    mydb.commit()\n",
        "    t4=cursor.fetchall()\n",
        "    df4=pd.DataFrame(t4,columns=[\"no of comments\",\"videotitle\"])\n",
        "    st.write(df4)\n",
        "\n",
        "elif question==\"5. videos with highest likes\":\n",
        "    query5='''select title as videotitle,channel_name as channelname,likes as likecount\n",
        "                from videos where likes is not null order by likes desc'''\n",
        "    cursor.execute(query5)\n",
        "    mydb.commit()\n",
        "    t5=cursor.fetchall()\n",
        "    df5=pd.DataFrame(t5,columns=[\"videotitle\",\"channelname\",\"likecount\"])\n",
        "    st.write(df5)\n",
        "\n",
        "elif question==\"6. likes of all videos\":\n",
        "    query6='''select likes as likecount,title as videotitle from videos'''\n",
        "    cursor.execute(query6)\n",
        "    mydb.commit()\n",
        "    t6=cursor.fetchall()\n",
        "    df6=pd.DataFrame(t6,columns=[\"likecount\",\"videotitle\"])\n",
        "    st.write(df6)\n",
        "\n",
        "elif question==\"7. views of each channel\":\n",
        "    query7='''select channel_names as channelname,views as totalviews from channels'''\n",
        "    cursor.execute(query7)\n",
        "    mydb.commit()\n",
        "    t7=cursor.fetchall()\n",
        "    df7=pd.DataFrame(t7,columns=[\"channel name\",\"totalviews\"])\n",
        "    st.write(df7)\n",
        "\n",
        "elif question==\"8. videos published in the year of 2022\":\n",
        "    query8='''select title as video_title,published_date as videorelease,channel_name as channelname from videos\n",
        "              where extract(year from published_date)=2022'''\n",
        "    cursor.execute(query8)\n",
        "    mydb.commit()\n",
        "    t8=cursor.fetchall()\n",
        "    df8=pd.DataFrame(t8,columns=[\"videotitle\",\"published_date\",\"channelname\"])\n",
        "    st.write(df8)\n",
        "\n",
        "elif question==\"9. average duration of all videos in each channel\":\n",
        "    query9='''select channel_name as channelname,AVG(duration) as averageduration from videos group by channel_name'''\n",
        "    cursor.execute(query9)\n",
        "    mydb.commit()\n",
        "    t9=cursor.fetchall()\n",
        "    df9=pd.DataFrame(t9,columns=[\"channelname\",\"averageduration\"])\n",
        "\n",
        "    T9=[]\n",
        "    for index,row in df9.iterrows():\n",
        "        channel_title=row[\"channelname\"]\n",
        "        average_duration=row[\"averageduration\"]\n",
        "        average_duration_str=str(average_duration)\n",
        "        T9.append(dict(channeltitle=channel_title,avgduration=average_duration_str))\n",
        "    df1=pd.DataFrame(T9)\n",
        "    st.write(df1)\n",
        "\n",
        "elif question==\"10. videos with highest number of comments\":\n",
        "    query10='''select title as videotitle,channel_name as channelname,comments as comments from videos\n",
        "            where comments is not null order by comments desc'''\n",
        "    cursor.execute(query10)\n",
        "    mydb.commit()\n",
        "    t10=cursor.fetchall()\n",
        "    df10=pd.DataFrame(t10,columns=[\"video title\",\"channel name\",\"comments\"])\n",
        "    st.write(df10)\n",
        "\n",
        ""
      ]
    }
  ]
}